Table users {
  id varchar [pk]
  email varchar [unique, not null]
  username varchar [not null]
  phone_number varchar
  password varchar [not null]
  role varchar
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime
}

Table files {
  id varchar [pk]
  file_name varchar [not null]
  file_url varchar [not null]
  uploaded_by varchar [not null, ref: > users.id]
  uploaded_at datetime [default: `CURRENT_TIMESTAMP`]
}

Table todos {
  id varchar [pk]
  title varchar [not null]
  description text
  category varchar [ref: > categories.id]
  date date [not null]
  status varchar [default: 'pending']
  is_recurring boolean [default: false]
  repeat varchar
  original_date date
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  completed_at datetime
  user_id varchar [not null, ref: > users.id]
  main_todo_id varchar [ref: > todos.id]
  recurrence_id varchar [ref: > todo_recurrences.id]
}

Table todo_recurrences {
  id varchar [pk]
  main_todo_id varchar [not null, ref: > todos.id]
  pattern varchar [not null]
  next_date date [not null]
  original_date date [not null]
  is_active boolean [default: true]
  user_id varchar [not null, ref: > users.id]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  last_completed_date date
}

Table categories {
  id varchar [pk]
  name varchar [not null]
  color varchar [not null]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  user_id varchar [not null, ref: > users.id]
}

Table sessions {
  id varchar [pk] 
  user_id varchar [not null, ref: > users.id] 
  token varchar [not null] 
  device varchar 
  ip_address varchar 
  user_agent text 
  is_active boolean [default: true] 
  created_at datetime [default: `CURRENT_TIMESTAMP`] 
  last_accessed datetime [default: `CURRENT_TIMESTAMP`] 
  expires_at datetime [not null] 
}